In [2]:
import numpy as np

# Step Function
def step(x):
    return np.where(x >= 0, 1, -1)
# Step 1: Define Pattern Pairs
# X patterns (Set A)
X1 = np.array([1, 1, 1])
X2 = np.array([-1, -1, -1])

# Y patterns (Set B)
Y1 = np.array([1, 1, 1, 1, 1, 1])
Y2 = np.array([-1, -1, -1, -1, -1, -1])


# Step 2: Create Weight Matrix
W = np.outer(X1, Y1) + np.outer(X2, Y2)
print("Weight Matrix:\n", W)
# Step 3: Testing Function
def BAM_recall(X_input, W):
    X = X_input
    
    for _ in range(5):   # iterate until convergence
        Y = step(np.dot(X, W))
        X = step(np.dot(Y, W.T))
    
    return X, Y
# Step 4: Test with Input
test_input = np.array([-1, -1, -1])

X_out, Y_out = BAM_recall(test_input, W)

print("\nInput X:", test_input)
print("Recalled Y:", Y_out)

Weight Matrix:
 [[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]

Input X: [-1 -1 -1]
Recalled Y: [-1 -1 -1 -1 -1 -1]
